### PR TITLE
Fix wrong item index being returned

### LINKED ISSUE #132: `getItemIndex()` returns index instead of NO_ID
`getItemIndex` should only return something else than `NO_ID` if `hasStableIds()` is set. We returned `index` as the default even with `setStableIds()` as false.

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #132 

Also update dependencies and based on external feedback the example project so it is more readable at a glance.

### CODE REVIEW

File: example/src/main/java/io/realm/examples/adapters/ui/recyclerview/MyRecyclerViewAdapter.java [hunk 1]
```diff
@@ -30,15 +30,19 @@
...
-class MyRecyclerViewAdapter extends RealmRecyclerViewAdapter<Counter, MyRecyclerViewAdapter.MyViewHolder> {
+class MyRecyclerViewAdapter extends RealmRecyclerViewAdapter<Item, MyRecyclerViewAdapter.MyViewHolder> {
 
     private boolean inDeletionMode = false;
     private Set<Integer> countersToDelete = new HashSet<Integer>();
 
-    MyRecyclerViewAdapter(OrderedRealmCollection<Counter> data) {
+    MyRecyclerViewAdapter(OrderedRealmCollection<Item> data) {
         super(data, true);
+        // Only set this if the model class has a primary key that is also a integer or long.
```
Comment (nhachicha) [inline example/src/main/java/io/realm/examples/adapters/ui/recyclerview/MyRecyclerViewAdapter.java]: an integer
